In [2]:
import numpy as np
A = np.asarray([[-1, 5, 8], [4, -15, -12], [3, -11, -8], [-2, 9, 12]])

In [3]:
A.shape

(4, 3)

In [4]:
A_pinv = np.linalg.pinv(A) * 16744

In [5]:
A_pinv

array([[  544.,   484.,   496.,   556.],
       [-1214., -1234., -1230., -1210.],
       [ 1672.,   872.,  1032.,  1832.]])

In [25]:
(A @ A_pinv @ A) / 16744

array([[ -1.,   5.,   8.],
       [  4., -15., -12.],
       [  3., -11.,  -8.],
       [ -2.,   9.,  12.]])

In [18]:
def bmatrix(a: np.ndarray) -> str:
    a = a.astype(int)
    lines = str(a).replace('[', '').replace(']', '').splitlines()
    rv = [r"\begin{bmatrix}"]
    rv += [' ' + '&'.join(l.split()) for l in lines]
    rv += [r"\end{bmatrix}"]
    return ''.join(rv)

In [26]:
A = np.asarray([[-2, 10, 13, -5], [4, -14, -1, 11], [3, -10, 0, 15], [-1, 6, 12, -9]])

In [27]:
np.linalg.pinv(A)

array([[-0.01276264,  0.02478661, -0.00899746,  0.02102142],
       [ 0.05642646, -0.08305975,  0.03998071, -0.066614  ],
       [ 0.03418418,  0.03168089,  0.0172665 ,  0.04859857],
       [ 0.05683684, -0.04366382,  0.0784533 , -0.06528029]])

In [29]:
np.linalg.det(A)

5.68434188608082e-14

In [32]:
18-54+15

-21

In [38]:
A = np.asarray([[-2, 10, 13, -5],
                [4, -14, -1, 11],
                [3, -10, 0, 15],
                [-1, 6, 12, -9]])
F = np.asarray([[-2, 10, 13],
                [4, -14, -1],
                [3, -10, 0],
                [-1, 6, 12]])

G = np.asarray([[1, 0, 0, 75],
                [0, 1, 0, 21],
                [0, 0, 1, -5]])

In [39]:
F @ G

array([[ -2,  10,  13,  -5],
       [  4, -14,  -1,  11],
       [  3, -10,   0,  15],
       [ -1,   6,  12,  -9]])

In [41]:
gramm_g = G @ G.T

In [45]:
inv_gramm_g = np.linalg.inv(gramm_g) * np.linalg.det(gramm_g)

In [47]:
G.T @ inv_gramm_g

array([[ 4.670e+02, -1.575e+03,  3.750e+02],
       [-1.575e+03,  5.651e+03,  1.050e+02],
       [ 3.750e+02,  1.050e+02,  6.067e+03],
       [ 7.500e+01,  2.100e+01, -5.000e+00]])

In [49]:
gramm_f = F.T @ F
inv_gramm_g = np.linalg.inv(gramm_f) * np.linalg.det(gramm_f)

In [50]:
np.linalg.det(gramm_g) * np.linalg.det(gramm_f)

6238207.999999593

In [51]:
np.linalg.det(gramm_f)

1023.9999999998827

In [52]:
np.linalg.det(gramm_g)

6092.0000000003

In [53]:
1024*6092

6238208

In [63]:
np.linalg.pinv(A) * 97472

array([[-1244.,  2416.,  -877.,  2049.],
       [ 5500., -8096.,  3897., -6493.],
       [ 3332.,  3088.,  1683.,  4737.],
       [ 5540., -4256.,  7647., -6363.]])

In [62]:
6238208 / 64

97472.0

In [64]:
b = np.asarray([1, 6, 9, 4])

In [84]:
ans = np.linalg.pinv(A) @ b

In [87]:
for i in range(A.shape[0]):
    print(A[i, :] @ ans, "=", b[i]) 

2.4999999999999982 = 1
7.500000000000002 = 6
7.500000000000003 = 9
2.4999999999999956 = 4


In [95]:
check = np.linalg.pinv(A) @ A - np.identity(4)

In [103]:
np.set_printoptions(suppress=True)

In [104]:
check

array([[-0.92334209, -0.25853578,  0.06155614,  0.01231123],
       [-0.25853578, -0.07239002,  0.01723572,  0.00344714],
       [ 0.06155614,  0.01723572, -0.00410374, -0.00082075],
       [ 0.01231123,  0.00344714, -0.00082075, -0.00016415]])

In [100]:
float(-2.58535785e-01)

-0.258535785

In [105]:
A = np.asarray([[-46, -3, 68, -28], 
                [2, 54, -76, 32],
                [25, -102, -20, -44]])

In [106]:
A.T @ A

array([[ 2745, -2304, -3780,   252],
       [-2304, 13329, -2268,  6300],
       [-3780, -2268, 10800, -3456],
       [  252,  6300, -3456,  3744]])

In [107]:
import array_to_latex as a2l


In [283]:
a2l.to_clp(np.linalg.pinv(A), frmt = '{0:2f}', arraytype = 'bmatrix')

In [282]:
\begin{bmatrix}
 -0.021948 & -0.017833 & -0.006859\\
  0.000823 &  0.002469 & -0.006584\\
 -0.005075 & -0.015569 & -0.008093\\
 -0.012071 & -0.008779 & -0.007682
\end{bmatrix}

array([[-0.02194787, -0.01783265, -0.00685871],
       [ 0.00082305,  0.00246914, -0.00658436],
       [-0.00507545, -0.01556927, -0.00809328],
       [-0.01207133, -0.00877915, -0.00768176]])

In [111]:
import scipy
import math

In [246]:
def f3(x):
    return (2*x**2-1)*math.sqrt(5*x+12) / math.sqrt(1-x**2)

def f4(x):
    return (4*x**3-3*x)*math.sqrt(5*x+12) / math.sqrt(1-x**2)

In [272]:
x = np.linspace(-0.99999999, 0.99999999, 10000000)

In [275]:
y = [f4(x_) for x_ in x]

In [278]:
scipy.integrate.quad(f3, -1, 1)

C:\Users\Aleksey Ryabykin\AppData\Local\Temp\ipykernel_24144\3701147324.py:1: IntegrationWarning: The integral is probably divergent, or slowly convergent.
  scipy.integrate.quad(f3, -1, 1)


(-0.06255199431786816, 2.9274116047917076e-09)

In [ ]:
-0.061028772041909124

In [ ]:
0.007137857666674491

In [284]:
import pandas as pd
import numpy as np
from sklearn import datasets

In [289]:
boston = datasets.load_boston();

In [291]:
X = boston.data
y = boston.target

In [292]:
df = pd.DataFrame(X)
df.sample(3)

0     1      2    3      4      5     6       7    8      9     10  \
164  2.24236   0.0  19.58  0.0  0.605  5.854  91.8  2.4220  5.0  403.0  14.7   
284  0.00906  90.0   2.97  0.0  0.400  7.088  20.8  7.3073  1.0  285.0  15.3   
200  0.01778  95.0   1.47  0.0  0.403  7.135  13.9  7.6534  3.0  402.0  17.0   

         11     12  
164  395.11  11.64  
284  394.72   7.85  
200  384.30   4.45

In [301]:
cor_matrix = df.corr().abs()
upper = cor_matrix.where(np.triu(np.ones(cor_matrix.shape), k=1).astype(bool))

In [296]:
upper

0         1         2         3         4         5         6         7   \
0  NaN  0.200469  0.406583  0.055892  0.420972  0.219247  0.352734  0.379670   
1  NaN       NaN  0.533828  0.042697  0.516604  0.311991  0.569537  0.664408   
2  NaN       NaN       NaN  0.062938  0.763651  0.391676  0.644779  0.708027   
3  NaN       NaN       NaN       NaN  0.091203  0.091251  0.086518  0.099176   
4  NaN       NaN       NaN       NaN       NaN  0.302188  0.731470  0.769230   
5  NaN       NaN       NaN       NaN       NaN       NaN  0.240265  0.205246   
6  NaN       NaN       NaN       NaN       NaN       NaN       NaN  0.747881   
7  NaN       NaN       NaN       NaN       NaN       NaN       NaN       NaN   
8  NaN       NaN       NaN       NaN       NaN       NaN       NaN       NaN   
9  NaN       NaN       NaN       NaN       NaN       NaN       NaN       NaN   
10 NaN       NaN       NaN       NaN       NaN       NaN       NaN       NaN   
11 NaN       NaN       NaN       NaN       NaN       NaN       NaN       NaN   
12 NaN       NaN       NaN       NaN       NaN       NaN       NaN       NaN   

          8         9         10        11        12  
0   0.625505  0.582764  0.289946  0.385064  0.455621  
1   0.311948  0.314563  0.391679  0.175520  0.412995  
2   0.595129  0.720760  0.383248  0.356977  0.603800  
3   0.007368  0.035587  0.121515  0.048788  0.053929  
4   0.611441  0.668023  0.188933  0.380051  0.590879  
5   0.209847  0.292048  0.355501  0.128069  0.613808  
6   0.456022  0.506456  0.261515  0.273534  0.602339  
7   0.494588  0.534432  0.232471  0.291512  0.496996  
8        NaN  0.910228  0.464741  0.444413  0.488676  
9        NaN       NaN  0.460853  0.441808  0.543993  
10       NaN       NaN       NaN  0.177383  0.374044  
11       NaN       NaN       NaN       NaN  0.366087  
12       NaN       NaN       NaN       NaN       NaN

In [297]:
columns_to_drop = [column for column in upper.columns if any(upper[column] > 0.5)]
print(columns_to_drop)

[2, 4, 6, 7, 8, 9, 12]


In [299]:
df.drop(df.columns[columns_to_drop], axis=1)

0     1    3      5     10      11
0    0.00632  18.0  0.0  6.575  15.3  396.90
1    0.02731   0.0  0.0  6.421  17.8  396.90
2    0.02729   0.0  0.0  7.185  17.8  392.83
3    0.03237   0.0  0.0  6.998  18.7  394.63
4    0.06905   0.0  0.0  7.147  18.7  396.90
..       ...   ...  ...    ...   ...     ...
501  0.06263   0.0  0.0  6.593  21.0  391.99
502  0.04527   0.0  0.0  6.120  21.0  396.90
503  0.06076   0.0  0.0  6.976  21.0  396.90
504  0.10959   0.0  0.0  6.794  21.0  393.45
505  0.04741   0.0  0.0  6.030  21.0  396.90

[506 rows x 6 columns]